#!/bin/bash

/root/anaconda3/envs/pycrispr/bin/python -m pybasespace.app



#echo ========================================
#echo              APP RESULTS
#echo ========================================

#echo ' _metadata.json'
#echo -----------------
#jq '.' /data/output/appresults/*/*/_metadata.json
#echo
#echo 'appsession_params.csv'
#echo -----------------------
#cat /data/output/appresults/*/*/appsessionparams.csv
#echo
#echo 'payloadresult.txt'
#echo -------------------
#cat /data/output/appresults/*/*/payload_result.txt
#echo
#echo ls -la'/data/output/appresults'
#echo -------------------------------
#ls -la /data/output/appresults/*/*/*
#echo
#echo ========================================
