#!/bin/bash

# not working!?
#source activate pycrispr

export PATH="$PATH:/opt/blast/bin"

export BLASTDB=/RESTORE/
export GENOMES=/GENOMES/
export PROTOSP=/RESTORE/
export SCRATCH=/data/scratch/
export APPSESS=/data/input/AppSession.json

echo
echo BLASTDB is now $BLASTDB
echo GENOMES is now $GENOMES
echo PROTOSP is now $PROTOSP
echo SCRATCH is now $SCRATCH
echo APPSESS is now $APPSESS
echo

cat /root/hello.txt

# pip uninstall -y pycrispry
# pip install  git+https://github.com/alaindomissy/buffet.git#egg=pycrispr
# pip install primer3-py

/root/bin/app
